name: Run start-wars demo web and api tests

on:
  push:
    branches:
      - master

jobs:
  run_Tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version:
          - '3.11'

    permissions:
      checks: write

    name: Test web and api
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout development repo and start the server
        run: |
          brew install node
          git clone https://github.com/MindfulMichaelJames/star-wars.git
          cd star-wars
          npm install yarn
          yarn install
          yarn build
          yarn start >/dev/null &
          cd ..

      #      - name: Checkout repository
      #        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          brew install --cask google-chrome
          python -m pip install --upgrade pip
          python -m pip install selenium
          python -m pip install webdriver_manager
          python -m pip install -U pytest
          python -m pip install pytest-html
          python -m pip install requests

      - name: Run the tests
        run: |
          git clone https://github.com/MrDevinders/StartWarsTest.git
          cd StartWarsTest
          python -m pytest -v
          killall node
          git config user.name MrDevinders
          git config user.email MrDevinders@Gmail.com
          git add --all
          git commit -m "Report"
          git push
      #          python -m pytest -v -m web
      #          python -m pytest -v -m api

      - name: Publish report
        run: |
